-- 1.What is the total revenue generated by male vs female customers?
select Gender, sum(Amount*Qty) as total_revenue from clothes
group by Gender;

 -- 2.What is the average revenue per order?
SELECT AVG(order_value) AS avg_order_value
FROM (SELECT Order_ID, SUM(Amount*Qty) AS order_value FROM clothes
    GROUP BY Order_ID) t;

-- 3.How many customers belong to each gender group?
SELECT Gender,COUNT(DISTINCT Cust_ID) AS total_customers from clothes
GROUP BY Gender;

-- 4.Which age group generates the most customers and revenue?
SELECT age_group,COUNT(DISTINCT Cust_ID) AS customers, SUM(Amount*Qty) AS revenue FROM clothes
GROUP BY age_group
ORDER BY revenue DESC;

-- 5.Which product categories generate the highest revenue?
select Category,SUM(Amount*Qty) AS revenue from clothes
GROUP BY Category
order by revenue  desc limit 5;

-- 6.Which clothing sizes sell the most?
SELECT Size,SUM(Qty) AS total_sold FROM clothes
GROUP BY Size
ORDER BY total_sold DESC limit 3;

-- 7.How are orders distributed across different statuses?
SELECT Status,COUNT(DISTINCT Order_ID) AS total_orders FROM clothes
GROUP BY Status
ORDER BY total_orders DESC;

-- 8.What percentage of total orders gets cancelled?
SELECT ROUND(100.0 * COUNT(DISTINCT CASE WHEN Status = 'Cancelled' THEN Order_ID END)/ COUNT(DISTINCT Order_ID),2) AS cancellation_rate
FROM clothes;

-- 9.Which states have the highest number of orders?
SELECT ship_state,COUNT(DISTINCT Order_ID) AS total_orders FROM clothes
GROUP BY ship_state
ORDER BY total_orders DESC limit 5;

-- 10.Which sales channel generates the most orders and revenue?
select Channel,count( distinct Order_ID) as total_orders ,sum(Amount*Qty) as revenue from clothes
group by Channel 
order by revenue desc ;

-- 11.What is the revenue comparison between B2B and non-B2B orders?
SELECT B2B,COUNT(DISTINCT Order_ID) AS total_orders,SUM(Amount * Qty) AS revenue, SUM(Amount * Qty) / COUNT(DISTINCT Order_ID) AS avg_order_value
FROM clothes
GROUP BY B2B
ORDER BY revenue DESC;

-- 12.How many customers place more than one order?
SELECT COUNT(*) AS repeat_customers FROM (SELECT Cust_ID FROM clothes
    GROUP BY Cust_ID
    HAVING COUNT(DISTINCT Order_ID) > 1) t;
    
-- 13.Which customers generate the highest total revenue?
select  Cust_ID, SUM(Amount * Qty) AS revenue from clothes
group by Cust_ID
order by revenue desc limit 5;

-- 14.On average, how many items does a customer purchase in each order?
SELECT AVG(items_per_order) AS avg_items_per_order FROM (SELECT Order_ID,Cust_ID, SUM(Qty) AS items_per_order FROM clothes
    GROUP BY Order_ID, Cust_ID) t;










